apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: vernissage
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: vernissage-postgres
  sessionAffinity: None
  type: ClusterIP
