apiVersion: v1
data:
  POSTGRES_DB: vernissage-db
  POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD_HERE
  POSTGRES_USER: vernissage-user
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: vernissage
