apiVersion: v1
kind: Service
metadata:
  name: vernissage-proxy
  namespace: vernissage
  labels:
    app: vernissage
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: proxy
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vernissage-proxy
  sessionAffinity: None
  type: ClusterIP
