apiVersion: v1
kind: Service
metadata:
  name: vernissage-redis
  namespace: vernissage
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: vernissage-redis
  sessionAffinity: None
  type: ClusterIP
