apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vernissage-api
  name: vernissage-api
  namespace: vernissage
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vernissage-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vernissage-api
      namespace: vernissage
    spec:
      affinity: {}
      containers:
        - envFrom:
            - configMapRef:
                name: env
                optional: false
          image: mczachurski/vernissage-server:latest
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: vernissage-api
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      subdomain: internal
      terminationGracePeriodSeconds: 30
