apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: vernissage-push
  name: vernissage-push
  namespace: vernissage
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: vernissage-push
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vernissage
        component: vernissage-push
      namespace: vernissage
    spec:
      affinity: {}
      containers:
        - envFrom:
            - configMapRef:
                name: env
                optional: false
          image: mczachurski/vernissage-push:latest
          imagePullPolicy: Always
          name: push
          ports:
            - containerPort: 3000
              name: push
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: vernissage-push
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      subdomain: internal
      terminationGracePeriodSeconds: 30
