apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: vernissage-web
  name: vernissage-web
  namespace: vernissage
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: vernissage-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2025-06-14T01:01:33Z'
      labels:
        app: vernissage
        component: vernissage-web
      namespace: vernissage
    spec:
      affinity: {}
      containers:
        - envFrom:
            - configMapRef:
                name: env
                optional: false
          image: mczachurski/vernissage-web:latest
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: vernissage-web
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      subdomain: internal
      terminationGracePeriodSeconds: 30
