apiVersion: v1
kind: Service
metadata:
  name: vernissage-web
  namespace: vernissage
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vernissage-web
  sessionAffinity: None
  type: ClusterIP
