apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vernissage-redis
  name: vernissage-redis
  namespace: vernissage
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vernissage-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vernissage-redis
      namespace: vernissage
    spec:
      affinity: {}
      containers:
        - command:
            - redis-server
          image: redis
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
                - '|'
                - grep
                - PONG
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: vernissage-redis
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      subdomain: internal
      terminationGracePeriodSeconds: 30
